### ISSUE TITLE
Adjust readme title

### ISSUE THREAD

**Issue by MfundoZA** [MfundoZA/TheRideYouRent#1]
Make readme title one word

**Comment by 07jhashubham** [comment]
Which readme. MD file title you want to be adjusted? I can't get it...

**Comment by MfundoZA** [comment]
The readme file here (https://github.com/MfundoZA/TheRideYouRent/blob/master/readme.md)

the very first line is inconsistent with the other times the company name is written. So it needs to say "TheRideYouRent" instead of "The Ride You Rent"

**Comment by 07jhashubham** [comment]
Ok. Assing me. I'll do it

**Comment by MfundoZA** [comment]
It's assigned to you. Go for it
